[[language]]
name = "rust"
auto-format = true

[[language]]
name = "typescript"
language-server = { command = "deno", args = ["lsp"] }
config = { enable = true, unstable = true }

[[language]]
name = "typescript"
language-server = { command = "deno", args = ["lsp"]}
config = { enable = true, unstable = true }

[[language]]
name = "fish"
formatter = {command = "fish_indent"}
auto-format = true
